"""Constants for the application."""

DEFAULT_MAX_TOKENS = 250
DEFAULT_LLM_TIMEOUT = 600
DEFAULT_MAX_RETRIES = 3

RETRY_MAX_ATTEMPTS = 5
RETRY_MIN_WAIT = 2
RETRY_MAX_WAIT = 60
RETRY_MULTIPLIER = 1

REQUEST_ID_PREFIX_LLM = "llm"
REQUEST_ID_PREFIX_TOOL = "tool"

LOG_CONTENT_PREVIEW_LENGTH = 200
LOG_RESPONSE_PREVIEW_LENGTH = 500
LOG_ERROR_RESPONSE_LENGTH = 1000