name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

defaults:
  run:
    working-directory: backend

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "backend/uv.lock"
    
    - name: Install dependencies
      run: uv sync --frozen
    
    - name: Run ruff linting
      run: |
        uv run ruff check .
        uv run ruff format --check .
    
    - name: Run tests with coverage
      run: |
        uv run pytest tests/ -v --cov=app --cov-report=term-missing --cov-report=html --cov-report=xml
      env:
        PYTHONPATH: ${{ github.workspace }}/backend
        ENVIRONMENT: test
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: backend/htmlcov/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: backend/coverage.xml
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false